### ISSUE TITLE
Dublicate files produced by EITI data harvester

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#8] opened 2017-04-13 16:33 UTC
![image](https://cloud.githubusercontent.com/assets/1101585/25014343/57123bd0-2045-11e7-9333-64230c51f72e.png)

Link: http://resourcedata.org/dataset/eiti-summary-data-table-for-democratic-republic-of-congo

We should only have one file here to avoid confusion.

**Comment by iprunache** [comment] 2017-04-20 20:39
Seems to be caused by the harvester failing to properly update the datasets for 4 countries:

```
Apr 13 17:49:49 2da64ca63ca3 ecs-eiti-harvester-master-task-11-eiti-harvester-master-containe:  409 {u'help': u'http://www.resourcedata.org/api/3/action/help_show?name=package_update', u'success': False, u'error': {u'country': [u"Value must be one of: Aruba; Afghanistan; Angola; Anguilla; \xc5land Islands; Albania; Andorra; Netherlands Antilles; United Arab Emirates; Argentina; Armenia; American Samoa; Antarctica; French Southern Territories; Antigua and Barbuda; Australia; Austria; Azerbaijan; Burundi; Belgium; Benin; Burkina Faso; Bangladesh; Bulgaria; Bahrain; Bahamas; Bosnia and Herzegovina; Saint Barth\xe9lemy; Belarus; Belize; Bermuda; Bolivia, Plurinational State of; Brazil; Barbados; Brunei Darussalam; Bhutan; Bouvet Island; Botswana; Central African Republic; Canada; Cocos (Keeling) Islands; Switzerland; Chile; China; C\xf4te d'Ivoire; Cameroon; Congo, the Democratic Republic of the; Congo; Cook Islands; Colombia; Comoros; Cape Verde; Costa Rica; Cuba; Christmas Island; Cayman Islands; Cyprus; Czech Republic; Germany; Djibouti; Dominica; Denmark; Dominican Republic; Algeria; Ecuador; Egypt; Eritrea; Western Sahara; Spain; Estonia; Ethiopia; Finland; Fiji; Falkland Islands (Malvinas); France; Faroe Islands; Micronesia, Federated States of; Gabon; United Kingdom; Georgia; Guernsey; Ghana; Gibraltar; Guinea; Guadeloupe; Gambia; Guinea-Bissau; Equatorial Guinea; Greece; Grenada; Greenland; Guatemala; French Guiana; Guam; Guyana; Hong Kong; Heard Island and McDonald Islands; Honduras; Croatia; Haiti; Hungary; Indonesia; Isle of Man; India; British Indian Ocean Territory; Ireland; Iran, Islamic Republic of; Iraq; Iceland; Israel; Italy; Jamaica; Jersey; Jordan; Japan; Kazakhstan; Kenya; Kyrgyzstan; Cambodia; Kiribati; Saint Kitts and Nevis; Korea, Republic of; Kuwait; Lao People's Democratic Republic; Lebanon; Liberia; Libyan Arab Jamahiriya; Saint Lucia; Liechtenstein; Sri Lanka; Lesotho; Lithuania; Luxembourg; Latvia; Macao; Saint Martin (French part); Morocco; Monaco; Moldova, Republic of; Madagascar; Maldives; Mexico; Marshall Islands; Macedonia, the former Yugoslav Republic of; Mali; Malta; Myanmar; Montenegro; Mongolia; Northern Mariana Islands; Mozambique; Mauritania; Montserrat; Martinique; Mauritius; Malawi; Malaysia; Mayotte; Namibia; New Caledonia; Niger; Norfolk Island; Nigeria; Nicaragua; Niue; Netherlands; Norway; Nepal; Nauru; New Zealand; Oman; Pakistan; Panama; Pitcairn; Peru; Philippines; Palau; Papua New Guinea; Poland; Puerto Rico; Korea, Democratic People's Republic of; Portugal; Paraguay; Palestinian Territory, Occupied; French Polynesia; Qatar; R\xe9union; Romania; Russian Federation; Rwanda; Saudi Arabia; Sudan; Senegal; Singapore; South Georgia and the South Sandwich Islands; Saint Helena, Ascension and Tristan da Cunha; Svalbard and Jan Mayen; Solomon Islands; Sierra Leone; El Salvador; San Marino; Somalia; Saint Pierre and Miquelon; Serbia; Sao Tome and Principe; Suriname; Slovakia; Slovenia; Sweden; Swaziland; Seychelles; Syrian Arab Republic; Turks and Caicos Islands; Chad; Togo; Thailand; Tajikistan; Tokelau; Turkmenistan; Timor-Leste; Tonga; Trinidad and Tobago; Tunisia; Turkey; Tuvalu; Taiwan, Province of China; Tanzania, United Republic of; Uganda; Ukraine; United States Minor Outlying Islands; Uruguay; United States; Uzbekistan; Holy See (Vatican City State); Saint Vincent and the Grenadines; Venezuela, Bolivarian Republic of; Virgin Islands, British; Virgin Islands, U.S.; Viet Nam; Vanuatu; Wallis and Futuna; Samoa; Yemen; South Africa; Zambia; Zimbabwe; South Sudan (not u'Democratic Republic of Congo')"], u'__type': u'Validation Error'}}
Apr 13 17:49:54 2da64ca63ca3 ecs-eiti-harvester-master-task-11-eiti-harvester-master-containe:  409 {u'help': u'http://www.resourcedata.org/api/3/action/help_show?name=package_update', u'success': False, u'error': {u'country': [u"Value must be one of: Aruba; Afghanistan; Angola; Anguilla; \xc5land Islands; Albania; Andorra; Netherlands Antilles; United Arab Emirates; Argentina; Armenia; American Samoa; Antarctica; French Southern Territories; Antigua and Barbuda; Australia; Austria; Azerbaijan; Burundi; Belgium; Benin; Burkina Faso; Bangladesh; Bulgaria; Bahrain; Bahamas; Bosnia and Herzegovina; Saint Barth\xe9lemy; Belarus; Belize; Bermuda; Bolivia, Plurinational State of; Brazil; Barbados; Brunei Darussalam; Bhutan; Bouvet Island; Botswana; Central African Republic; Canada; Cocos (Keeling) Islands; Switzerland; Chile; China; C\xf4te d'Ivoire; Cameroon; Congo, the Democratic Republic of the; Congo; Cook Islands; Colombia; Comoros; Cape Verde; Costa Rica; Cuba; Christmas Island; Cayman Islands; Cyprus; Czech Republic; Germany; Djibouti; Dominica; Denmark; Dominican Republic; Algeria; Ecuador; Egypt; Eritrea; Western Sahara; Spain; Estonia; Ethiopia; Finland; Fiji; Falkland Islands (Malvinas); France; Faroe Islands; Micronesia, Federated States of; Gabon; United Kingdom; Georgia; Guernsey; Ghana; Gibraltar; Guinea; Guadeloupe; Gambia; Guinea-Bissau; Equatorial Guinea; Greece; Grenada; Greenland; Guatemala; French Guiana; Guam; Guyana; Hong Kong; Heard Island and McDonald Islands; Honduras; Croatia; Haiti; Hungary; Indonesia; Isle of Man; India; British Indian Ocean Territory; Ireland; Iran, Islamic Republic of; Iraq; Iceland; Israel; Italy; Jamaica; Jersey; Jordan; Japan; Kazakhstan; Kenya; Kyrgyzstan; Cambodia; Kiribati; Saint Kitts and Nevis; Korea, Republic of; Kuwait; Lao People's Democratic Republic; Lebanon; Liberia; Libyan Arab Jamahiriya; Saint Lucia; Liechtenstein; Sri Lanka; Lesotho; Lithuania; Luxembourg; Latvia; Macao; Saint Martin (French part); Morocco; Monaco; Moldova, Republic of; Madagascar; Maldives; Mexico; Marshall Islands; Macedonia, the former Yugoslav Republic of; Mali; Malta; Myanmar; Montenegro; Mongolia; Northern Mariana Islands; Mozambique; Mauritania; Montserrat; Martinique; Mauritius; Malawi; Malaysia; Mayotte; Namibia; New Caledonia; Niger; Norfolk Island; Nigeria; Nicaragua; Niue; Netherlands; Norway; Nepal; Nauru; New Zealand; Oman; Pakistan; Panama; Pitcairn; Peru; Philippines; Palau; Papua New Guinea; Poland; Puerto Rico; Korea, Democratic People's Republic of; Portugal; Paraguay; Palestinian Territory, Occupied; French Polynesia; Qatar; R\xe9union; Romania; Russian Federation; Rwanda; Saudi Arabia; Sudan; Senegal; Singapore; South Georgia and the South Sandwich Islands; Saint Helena, Ascension and Tristan da Cunha; Svalbard and Jan Mayen; Solomon Islands; Sierra Leone; El Salvador; San Marino; Somalia; Saint Pierre and Miquelon; Serbia; Sao Tome and Principe; Suriname; Slovakia; Slovenia; Sweden; Swaziland; Seychelles; Syrian Arab Republic; Turks and Caicos Islands; Chad; Togo; Thailand; Tajikistan; Tokelau; Turkmenistan; Timor-Leste; Tonga; Trinidad and Tobago; Tunisia; Turkey; Tuvalu; Taiwan, Province of China; Tanzania, United Republic of; Uganda; Ukraine; United States Minor Outlying Islands; Uruguay; United States; Uzbekistan; Holy See (Vatican City State); Saint Vincent and the Grenadines; Venezuela, Bolivarian Republic of; Virgin Islands, British; Virgin Islands, U.S.; Viet Nam; Vanuatu; Wallis and Futuna; Samoa; Yemen; South Africa; Zambia; Zimbabwe; South Sudan (not u'Kyrgyz Republic')"], u'__type': u'Validation Error'}}
Apr 13 17:50:00 2da64ca63ca3 ecs-eiti-harvester-master-task-11-eiti-harvester-master-containe:  409 {u'help': u'http://www.resourcedata.org/api/3/action/help_show?name=package_update', u'success': False, u'error': {u'country': [u"Value must be one of: Aruba; Afghanistan; Angola; Anguilla; \xc5land Islands; Albania; Andorra; Netherlands Antilles; United Arab Emirates; Argentina; Armenia; American Samoa; Antarctica; French Southern Territories; Antigua and Barbuda; Australia; Austria; Azerbaijan; Burundi; Belgium; Benin; Burkina Faso; Bangladesh; Bulgaria; Bahrain; Bahamas; Bosnia and Herzegovina; Saint Barth\xe9lemy; Belarus; Belize; Bermuda; Bolivia, Plurinational State of; Brazil; Barbados; Brunei Darussalam; Bhutan; Bouvet Island; Botswana; Central African Republic; Canada; Cocos (Keeling) Islands; Switzerland; Chile; China; C\xf4te d'Ivoire; Cameroon; Congo, the Democratic Republic of the; Congo; Cook Islands; Colombia; Comoros; Cape Verde; Costa Rica; Cuba; Christmas Island; Cayman Islands; Cyprus; Czech Republic; Germany; Djibouti; Dominica; Denmark; Dominican Republic; Algeria; Ecuador; Egypt; Eritrea; Western Sahara; Spain; Estonia; Ethiopia; Finland; Fiji; Falkland Islands (Malvinas); France; Faroe Islands; Micronesia, Federated States of; Gabon; United Kingdom; Georgia; Guernsey; Ghana; Gibraltar; Guinea; Guadeloupe; Gambia; Guinea-Bissau; Equatorial Guinea; Greece; Grenada; Greenland; Guatemala; French Guiana; Guam; Guyana; Hong Kong; Heard Island and McDonald Islands; Honduras; Croatia; Haiti; Hungary; Indonesia; Isle of Man; India; British Indian Ocean Territory; Ireland; Iran, Islamic Republic of; Iraq; Iceland; Israel; Italy; Jamaica; Jersey; Jordan; Japan; Kazakhstan; Kenya; Kyrgyzstan; Cambodia; Kiribati; Saint Kitts and Nevis; Korea, Republic of; Kuwait; Lao People's Democratic Republic; Lebanon; Liberia; Libyan Arab Jamahiriya; Saint Lucia; Liechtenstein; Sri Lanka; Lesotho; Lithuania; Luxembourg; Latvia; Macao; Saint Martin (French part); Morocco; Monaco; Moldova, Republic of; Madagascar; Maldives; Mexico; Marshall Islands; Macedonia, the former Yugoslav Republic of; Mali; Malta; Myanmar; Montenegro; Mongolia; Northern Mariana Islands; Mozambique; Mauritania; Montserrat; Martinique; Mauritius; Malawi; Malaysia; Mayotte; Namibia; New Caledonia; Niger; Norfolk Island; Nigeria; Nicaragua; Niue; Netherlands; Norway; Nepal; Nauru; New Zealand; Oman; Pakistan; Panama; Pitcairn; Peru; Philippines; Palau; Papua New Guinea; Poland; Puerto Rico; Korea, Democratic People's Republic of; Portugal; Paraguay; Palestinian Territory, Occupied; French Polynesia; Qatar; R\xe9union; Romania; Russian Federation; Rwanda; Saudi Arabia; Sudan; Senegal; Singapore; South Georgia and the South Sandwich Islands; Saint Helena, Ascension and Tristan da Cunha; Svalbard and Jan Mayen; Solomon Islands; Sierra Leone; El Salvador; San Marino; Somalia; Saint Pierre and Miquelon; Serbia; Sao Tome and Principe; Suriname; Slovakia; Slovenia; Sweden; Swaziland; Seychelles; Syrian Arab Republic; Turks and Caicos Islands; Chad; Togo; Thailand; Tajikistan; Tokelau; Turkmenistan; Timor-Leste; Tonga; Trinidad and Tobago; Tunisia; Turkey; Tuvalu; Taiwan, Province of China; Tanzania, United Republic of; Uganda; Ukraine; United States Minor Outlying Islands; Uruguay; United States; Uzbekistan; Holy See (Vatican City State); Saint Vincent and the Grenadines; Venezuela, Bolivarian Republic of; Virgin Islands, British; Virgin Islands, U.S.; Viet Nam; Vanuatu; Wallis and Futuna; Samoa; Yemen; South Africa; Zambia; Zimbabwe; South Sudan (not u'Republic of the Congo')"], u'__type': u'Validation Error'}}
Apr 13 17:50:04 2da64ca63ca3 ecs-eiti-harvester-master-task-11-eiti-harvester-master-containe:  409 {u'help': u'http://www.resourcedata.org/api/3/action/help_show?name=package_update', u'success': False, u'error': {u'country': [u"Value must be one of: Aruba; Afghanistan; Angola; Anguilla; \xc5land Islands; Albania; Andorra; Netherlands Antilles; United Arab Emirates; Argentina; Armenia; American Samoa; Antarctica; French Southern Territories; Antigua and Barbuda; Australia; Austria; Azerbaijan; Burundi; Belgium; Benin; Burkina Faso; Bangladesh; Bulgaria; Bahrain; Bahamas; Bosnia and Herzegovina; Saint Barth\xe9lemy; Belarus; Belize; Bermuda; Bolivia, Plurinational State of; Brazil; Barbados; Brunei Darussalam; Bhutan; Bouvet Island; Botswana; Central African Republic; Canada; Cocos (Keeling) Islands; Switzerland; Chile; China; C\xf4te d'Ivoire; Cameroon; Congo, the Democratic Republic of the; Congo; Cook Islands; Colombia; Comoros; Cape Verde; Costa Rica; Cuba; Christmas Island; Cayman Islands; Cyprus; Czech Republic; Germany; Djibouti; Dominica; Denmark; Dominican Republic; Algeria; Ecuador; Egypt; Eritrea; Western Sahara; Spain; Estonia; Ethiopia; Finland; Fiji; Falkland Islands (Malvinas); France; Faroe Islands; Micronesia, Federated States of; Gabon; United Kingdom; Georgia; Guernsey; Ghana; Gibraltar; Guinea; Guadeloupe; Gambia; Guinea-Bissau; Equatorial Guinea; Greece; Grenada; Greenland; Guatemala; French Guiana; Guam; Guyana; Hong Kong; Heard Island and McDonald Islands; Honduras; Croatia; Haiti; Hungary; Indonesia; Isle of Man; India; British Indian Ocean Territory; Ireland; Iran, Islamic Republic of; Iraq; Iceland; Israel; Italy; Jamaica; Jersey; Jordan; Japan; Kazakhstan; Kenya; Kyrgyzstan; Cambodia; Kiribati; Saint Kitts and Nevis; Korea, Republic of; Kuwait; Lao People's Democratic Republic; Lebanon; Liberia; Libyan Arab Jamahiriya; Saint Lucia; Liechtenstein; Sri Lanka; Lesotho; Lithuania; Luxembourg; Latvia; Macao; Saint Martin (French part); Morocco; Monaco; Moldova, Republic of; Madagascar; Maldives; Mexico; Marshall Islands; Macedonia, the former Yugoslav Republic of; Mali; Malta; Myanmar; Montenegro; Mongolia; Northern Mariana Islands; Mozambique; Mauritania; Montserrat; Martinique; Mauritius; Malawi; Malaysia; Mayotte; Namibia; New Caledonia; Niger; Norfolk Island; Nigeria; Nicaragua; Niue; Netherlands; Norway; Nepal; Nauru; New Zealand; Oman; Pakistan; Panama; Pitcairn; Peru; Philippines; Palau; Papua New Guinea; Poland; Puerto Rico; Korea, Democratic People's Republic of; Portugal; Paraguay; Palestinian Territory, Occupied; French Polynesia; Qatar; R\xe9union; Romania; Russian Federation; Rwanda; Saudi Arabia; Sudan; Senegal; Singapore; South Georgia and the South Sandwich Islands; Saint Helena, Ascension and Tristan da Cunha; Svalbard and Jan Mayen; Solomon Islands; Sierra Leone; El Salvador; San Marino; Somalia; Saint Pierre and Miquelon; Serbia; Sao Tome and Principe; Suriname; Slovakia; Slovenia; Sweden; Swaziland; Seychelles; Syrian Arab Republic; Turks and Caicos Islands; Chad; Togo; Thailand; Tajikistan; Tokelau; Turkmenistan; Timor-Leste; Tonga; Trinidad and Tobago; Tunisia; Turkey; Tuvalu; Taiwan, Province of China; Tanzania, United Republic of; Uganda; Ukraine; United States Minor Outlying Islands; Uruguay; United States; Uzbekistan; Holy See (Vatican City State); Saint Vincent and the Grenadines; Venezuela, Bolivarian Republic of; Virgin Islands, British; Virgin Islands, U.S.; Viet Nam; Vanuatu; Wallis and Futuna; Samoa; Yemen; South Africa; Zambia; Zimbabwe; South Sudan (not u'Tanzania')"], u'__type': u'Validation Error'}}
Apr 13 17:50:06 2da64ca63ca3 ecs-eiti-harvester-master-task-11-eiti-harvester-master-containe:  409 {u'help': u'http://www.resourcedata.org/api/3/action/help_show?name=package_update', u'success': False, u'error': {u'country': [u"Value must be one of: Aruba; Afghanistan; Angola; Anguilla; \xc5land Islands; Albania; Andorra; Netherlands Antilles; United Arab Emirates; Argentina; Armenia; American Samoa; Antarctica; French Southern Territories; Antigua and Barbuda; Australia; Austria; Azerbaijan; Burundi; Belgium; Benin; Burkina Faso; Bangladesh; Bulgaria; Bahrain; Bahamas; Bosnia and Herzegovina; Saint Barth\xe9lemy; Belarus; Belize; Bermuda; Bolivia, Plurinational State of; Brazil; Barbados; Brunei Darussalam; Bhutan; Bouvet Island; Botswana; Central African Republic; Canada; Cocos (Keeling) Islands; Switzerland; Chile; China; C\xf4te d'Ivoire; Cameroon; Congo, the Democratic Republic of the; Congo; Cook Islands; Colombia; Comoros; Cape Verde; Costa Rica; Cuba; Christmas Island; Cayman Islands; Cyprus; Czech Republic; Germany; Djibouti; Dominica; Denmark; Dominican Republic; Algeria; Ecuador; Egypt; Eritrea; Western Sahara; Spain; Estonia; Ethiopia; Finland; Fiji; Falkland Islands (Malvinas); France; Faroe Islands; Micronesia, Federated States of; Gabon; United Kingdom; Georgia; Guernsey; Ghana; Gibraltar; Guinea; Guadeloupe; Gambia; Guinea-Bissau; Equatorial Guinea; Greece; Grenada; Greenland; Guatemala; French Guiana; Guam; Guyana; Hong Kong; Heard Island and McDonald Islands; Honduras; Croatia; Haiti; Hungary; Indonesia; Isle of Man; India; British Indian Ocean Territory; Ireland; Iran, Islamic Republic of; Iraq; Iceland; Israel; Italy; Jamaica; Jersey; Jordan; Japan; Kazakhstan; Kenya; Kyrgyzstan; Cambodia; Kiribati; Saint Kitts and Nevis; Korea, Republic of; Kuwait; Lao People's Democratic Republic; Lebanon; Liberia; Libyan Arab Jamahiriya; Saint Lucia; Liechtenstein; Sri Lanka; Lesotho; Lithuania; Luxembourg; Latvia; Macao; Saint Martin (French part); Morocco; Monaco; Moldova, Republic of; Madagascar; Maldives; Mexico; Marshall Islands; Macedonia, the former Yugoslav Republic of; Mali; Malta; Myanmar; Montenegro; Mongolia; Northern Mariana Islands; Mozambique; Mauritania; Montserrat; Martinique; Mauritius; Malawi; Malaysia; Mayotte; Namibia; New Caledonia; Niger; Norfolk Island; Nigeria; Nicaragua; Niue; Netherlands; Norway; Nepal; Nauru; New Zealand; Oman; Pakistan; Panama; Pitcairn; Peru; Philippines; Palau; Papua New Guinea; Poland; Puerto Rico; Korea, Democratic People's Republic of; Portugal; Paraguay; Palestinian Territory, Occupied; French Polynesia; Qatar; R\xe9union; Romania; Russian Federation; Rwanda; Saudi Arabia; Sudan; Senegal; Singapore; South Georgia and the South Sandwich Islands; Saint Helena, Ascension and Tristan da Cunha; Svalbard and Jan Mayen; Solomon Islands; Sierra Leone; El Salvador; San Marino; Somalia; Saint Pierre and Miquelon; Serbia; Sao Tome and Principe; Suriname; Slovakia; Slovenia; Sweden; Swaziland; Seychelles; Syrian Arab Republic; Turks and Caicos Islands; Chad; Togo; Thailand; Tajikistan; Tokelau; Turkmenistan; Timor-Leste; Tonga; Trinidad and Tobago; Tunisia; Turkey; Tuvalu; Taiwan, Province of China; Tanzania, United Republic of; Uganda; Ukraine; United States Minor Outlying Islands; Uruguay; United States; Uzbekistan; Holy See (Vatican City State); Saint Vincent and the Grenadines; Venezuela, Bolivarian Republic of; Virgin Islands, British; Virgin Islands, U.S.; Viet Nam; Vanuatu; Wallis and Futuna; Samoa; Yemen; South Africa; Zambia; Zimbabwe; South Sudan (not u'United States of America')"], u'__type': u'Validation Error'}}
```

/cc @mattfullerton

**Comment by mattfullerton** [comment] 2017-04-21 09:25
OK, looks like an easy fix

**Comment by anderspeders** [comment] 2017-04-26 19:35
@mattfullerton Could you follow up on this. Would like to get this closed up so that it can be circulated. 

Currently this is an issue of DRC, Kyrgyz Republic, Tanzania and US (according to @iprunache).

**Comment by mattfullerton** [comment] 2017-05-05 09:03
Closing in favour of #25

**Comment by moman822** [comment] 2017-06-20 18:58
@mattfullerton @iprunache this is back on the staging server

see: https://staging.resourcedata.org/dataset/eiti-summary-data-table-for-tanzania

**Comment by moman822** [comment] 2017-06-20 18:59
See #25 as before.

**Closed by moman822** 2017-06-20 18:59 UTC
Labels: bug
