### ISSUE TITLE
Table viewer no longer displays data

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#199] opened 2017-10-10 18:25 UTC
The table viewer is no longer showing data. 

See for example here: https://www.resourcedata.org/dataset/resource-revenue-data/resource/c4bf58d1-7f43-4a4f-b461-cd4aabf6041c

Any reason why we are having this issue?

Image: 
![image](https://user-images.githubusercontent.com/1101585/31403257-96b1747c-adc6-11e7-91e7-c23b2e6ef11d.png)

**Comment by mattfullerton** [comment] 2017-10-10 18:35
The issue is broken routes in CKAN and it is already fixed in https://github.com/ckan/ckan/commit/ddcc7cdb57474e7cd8b2d01148e8f4f8a14dbbee and on staging

**Comment by anderspeders** [comment] 2017-10-10 18:37
Amazing!

**Comment by mattfullerton** [comment] 2017-10-20 14:24
Fixed

**Closed by mattfullerton** 2017-10-20 14:24 UTC
Labels: bug, priority
