### ISSUE TITLE
EITI resources

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#192] opened 2017-09-20 09:58 UTC
EITI resources are not available for download. 

Get a '404 Not Found The resource could not be found. Resource data not found' error when trying to download data.

**Comment by iprunache** [comment] 2017-09-20 10:01
This looks like it was caused by going back to the S3 storage with the latest deploy.

@mattfullerton we should make sure that the EITI harvester is not again creating new resources for every dataset even if they haven't changed. What makes me think that this might be possible is that none of the current EITI resource IDs are not available on S3 so they must have changed.

**Comment by mattfullerton** [comment] 2017-09-20 12:08
Yes, see #169

**Comment by anderspeders** [comment] 2017-09-20 17:17
thanks for flagging @charlesyoung

**Comment by iprunache** [comment] 2017-09-21 07:09
The resources are back now since the EITI harvester finished running after Matt switched back to S3 storage. They are all downloaded from S3.

I'll close this issue once I confirm that the resource links don't change again when the EITI harvester finishes running today.

Here's a couple of current links for some resources, let's see if they change:
* https://www.resourcedata.org/dataset/985f7808-e561-417f-85bd-13ef26d794f2/resource/fd22a6d0-0d68-4dcf-821b-d8979e3eadad/download/company-payments-nigeria.csv
* https://www.resourcedata.org/dataset/10b5255e-e307-4b7a-b93e-5b681d5f6ee0/resource/5fe308ec-88cd-4d4d-b128-c5bfc87a2b83/download/company-payments-liberia.csv
* https://www.resourcedata.org/dataset/e4f9dc35-7b68-4b41-90ee-3e2411e2fd8f/resource/f187d688-4ee9-4792-b5e4-6625c638ff22/download/company-payments-ghana.csv

**Comment by mattfullerton** [comment] 2017-09-26 08:07
@iprunache Not looking good. I have reopened #169. The actual problem in this issue is solved. Thanks.

**Closed by mattfullerton** 2017-09-26 08:07 UTC
Labels: bug
