### ISSUE TITLE
GFS Code

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#167] opened 2017-08-15 10:58 UTC
Some of the GFS Code entries are recorded as scientific format resulting in below issue. 

![image](https://user-images.githubusercontent.com/13888372/29313198-02084f6e-81b9-11e7-8fc3-df2c7609c234.png)

**Comment by anderspeders** [comment] 2017-08-16 17:56
@mattfullerton @moman822 Any thoughts if this is on our end or if the issue is with the EITI API output?

**Comment by moman822** [comment] 2017-08-16 18:17
This is an issue with Excel converting the string to scientific notation, the output if you look in a text editor is correct (e.g. `11415E2`). Having looked at it, quoting the codes in the CSV (`"11415E2"` vs `11415E2`) has no effect in Excel (they are currently unquoted). Any solution that leaves the codes would be on user-end in Excel.

We could fix this by adding a dash or space in between: `11415-E2` or `11415 E2`.

**Comment by mattfullerton** [comment] 2017-08-31 10:59
@charlesyoung If only I'd read this issue before #145 - would have been great to keep this in a single issue

@moman822 Wow you just suggested a much easier fix for #145 - are they always in the format NUMBER-E-NUMBER? Then we can do that on the import side and datapusher won't have any problems.

In Excel, you should be able to fix that by doing a text import of the CSV instead of just directly opening it, there you can define column types. (Or use Open Office :tongue:)

The reason for the similar problem on the CKAN preview I have detailed in #145. Will paste your proposed solution in there and close this.

**Closed by mattfullerton** 2017-08-31 10:59 UTC
