### ISSUE TITLE
Add "country" to left search bar

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#7] opened 2017-04-13 16:30 UTC
![image](https://cloud.githubusercontent.com/assets/1101585/25014216/ced49010-2044-11e7-9704-9a274e15b65c.png)

Add "country" to the left search bar in order to improve navigation. 

For example here: http://resourcedata.org/organization/eiti

**Comment by mattfullerton** [comment] 2017-05-09 14:37
Duplicate of #27

**Closed by mattfullerton** 2017-05-09 14:37 UTC
Labels: enhancement
