### ISSUE TITLE
Change question numbers

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#135] opened 2017-07-13 16:00 UTC
The question numbers for documents are out-of-date and need to be updated. I will provide an excel file with the questions and old/new numbers to @mattfullerton.

See example below; new tag should be `1.2.7.a: Was the national tax authority audited over the most recently completed audit timeframe?`

![image](https://user-images.githubusercontent.com/19787025/28175504-6a624b20-67c2-11e7-9e55-cf7326d27a21.png)

![image](https://user-images.githubusercontent.com/19787025/28175530-82cf24da-67c2-11e7-95b2-3d609797ae43.png)

**Comment by mattfullerton** [comment] 2017-07-14 19:11
Have the question numbers from the resourcecontracts site API also changed or do we need to map them when we import?

**Comment by moman822** [comment] 2017-07-20 15:14
I do not know anything about resourcecontracts.org. How does this relate?

**Comment by mattfullerton** [comment] 2017-07-27 09:02
Fixed

**Comment by moman822** [comment] 2017-07-27 13:14
Some questions did not get changed. These are all the non-scoring questions which are at the bottom of the excel file highlighted in blue/green (row 208+).

![image](https://user-images.githubusercontent.com/19787025/28671791-e46693e2-72ab-11e7-913d-51f836db768f.png)

**Comment by mattfullerton** [comment] 2017-08-01 08:58
I only have the new question references in the list of valid questions for the import.

However, the problem is we now have PDFs already in there which are linked only to old questions and do not:
- Get updated with a new list of new question references, because they don't reference any of them
- Don't get deleted because we don't do a delete of all 9000+ PDFs before importing (sounds like a bad idea, and also is a bad idea because we would lose link persistence to resources and views).

You've already opened an issue to sort that out (#137) so I'd prefer to close this one...

**Closed** 2017-08-09 09:18 UTC
Labels: priority
