### ISSUE TITLE
User-uploaded resources destroyed/lost

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#168] opened 2017-08-16 19:02 UTC
All user uploaded resources were lost. This includes currently 5 Excel files and one CSV.

In the case of the CSV ([link](https://www.resourcedata.org/dataset/azer))

* The CSV file was lost but the file was viewable in the preview
* According to @mattfullerton " the preview still works but only because the datastore is working. The resource file download itself gives 404"
* Uploading a new file was successful, both for downloading and updating the previewer with the new file (tested by me). However, clicking "Upload" in the resource manager returns a 500 error page (but does not actually affect the upload)

For the Excel files ([link](https://www.resourcedata.org/dataset/latin-america-extractive-industry-contextual-data))

* The files and preview are both gone
* Trying to download the file gives 404 error ([link](https://www.resourcedata.org/dataset/18c1197d-fbd4-43eb-aea7-caa2e5cedfd6/resource/113ea5f8-6881-41eb-9968-624d08b31958/download/latam.xlsx))

**Comment by iprunache** [comment] 2017-08-17 07:12
I'll check if there were changes in how CKAN stores these early next week.

The 500 error on upload may be caused by a different reason.

@moman822 Could you attach or send the `CSV` by email so we can test uploading it?

**Comment by moman822** [comment] 2017-08-17 12:46
@iprunache the CSV is currently on there and working as expected (https://www.resourcedata.org/dataset/azer/resource/23b4fa19-c073-46c5-8579-e4a4355613ce)

Despite the 500 error when clicking "Upload", the file does get uploaded; it just diverts to the error page for some reason.

**Comment by mattfullerton** [comment] 2017-09-01 07:15
Can we keep this issue for the issue of resources disappearing and keep #180 for examining the upload problem? I'm happy to look at #180 as that's something I can easily test.

**Comment by moman822** [comment] 2017-09-18 18:44
This issue is persisting for the XLS files on ResourceData.org (user-uploaded CSVs seem Ok though).

All five excel files return "404 not found" see: https://www.resourcedata.org/dataset/bolivi/resource/7786bd8b-3725-45a0-a825-b0026539ab9b

Can we mark this as priority @mattfullerton @iprunache ?

**Comment by mattfullerton** [comment] 2017-09-19 18:46
@moman822 I haven't looked, but I'd be willing to be that the CSVs (files) are also gone and the previews are just working because they got imported into the datastore. I can look more closely tomorrow.

We must have a serious filestore/s3 store problem and this needs to be looked at by @iprunache or somebody from @NRGI/vitaminsoftware if he's still away

**Comment by mattfullerton** [comment] 2017-09-20 07:19
I think they're back: https://www.resourcedata.org/dataset/latin-america-extractive-industry-contextual-data/resource/113ea5f8-6881-41eb-9968-624d08b31958

But the logo for RGI (#191) isn't

**Comment by mattfullerton** [comment] 2017-09-20 08:04
OK then let's close this. I assume this was the problem all along. I've taken some action on our local git working copy to hopefully prevent this happening again.

**Closed by mattfullerton** 2017-09-20 08:04 UTC
Labels: Content, Deployment
