### ISSUE TITLE
Incorrect GFS Code

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#145] opened 2017-08-09 13:49 UTC
Below seems wrong. 

![image](https://user-images.githubusercontent.com/13888372/29124781-31f31db0-7d1a-11e7-8643-5567beed4ab9.png)

https://www.resourcedata.org/dataset/eiti-summary-data-table-for-papua-new-guinea/resource/3849e428-9223-42f5-96c7-f486347712c2

**Comment by mattfullerton** [comment] 2017-08-31 10:21
What's happening is that the datapusher which takes the CSV and pushes it to the datastore database guesses this column as numeric and then wreaks havoc. The problem is gfs_codes having "E"s at the end; this looks like scientific notation. You can see what field tyoes it guessed here: https://www.resourcedata.org/dataset/eiti-summary-data-table-for-papua-new-guinea/dictionary/3d1c3e9a-095b-48e9-b60e-c61cebf947d1

There is no easy solution to this. NOTE: The CSV files themselves are fine, we are talking here about the DB copy that is used for previewing and querying.

Workaounds/thoughts:
- Turn off automatic datapushing and add the data ourselves to the datastore. Would increase the duration of the import and is a significant amount of work (but less than a day).
- Don't show that column. Could be automated, but annoying because now we have to specify which columns to show instead of just "all". And the data are still wrong, just invisible.
- Set the data dictionary so that it'll get corrected one week later thanks to a recent change in CKAN (https://github.com/ckan/ckan/pull/3557) - can be done on a one off basis and should persist (but see/fix #169 first), or done every time as a closing stage of the import - although a new push should only happen when the data actually changes so we might have to force a push somehow in a script...
    - I've tested this by changing the dictionary and then doing the push again, for the resource above, on our dev server. It works: http://li1665-139.members.linode.com/dataset/eiti-summary-data-table-for-papua-new-guinea/resource/332412c2-6ef3-42ef-b791-6e42ef136a29
    - @iprunache We need to check what version of the datapusher you have deployed if we go down this road.
- Wait for CKAN to accept a dataset specification, or carry out this estimated piece of work ourselves (estimate from their side is 3 days):
https://github.com/frictionlessdata/ckanext-validation/issues/7 - this is obviously the most elegant solution, and it would be nice to populate those data dictionary fields with friendly explanatory labels like what a GFS code is.

**Comment by mattfullerton** [comment] 2017-08-31 10:22
Deliberately without milestone till we decide how to tackle this

**Comment by mattfullerton** [comment] 2017-08-31 11:00
@moman822 : We could fix this by adding a dash or space in between: 11415-E2 or 11415 E2.

Seems great to me if the codes really are always like that

**Comment by mattfullerton** [comment] 2017-09-01 08:22
We decided yesterday to try this approach, it'll become clear when it runs whether it works for all codes

**Comment by iprunache** [comment] 2017-09-21 07:28
@mattfullerton we're using v0.0.10 for datapusher. I see they're at 0.0.12 now.

**Comment by mattfullerton** [comment] 2017-09-21 08:21
@moman822 Looks like this will work well. Here's the full list of unique codes:
1412-E
114521-E
1422-E
144-E1
1212-E
1112-E1
1112-E2
15-E
1141-E
1413-E
1412-E2
1412-E1
1421-E
113-E
11451-E
1415-E
116-E
1415-E32
1415-E31
1151-E
1142-E
114522-E
1152-E
112-E
1153-E1
1415-E2
1415-E1
1415-E4
1415-E5
143-E

**Closed** 2017-09-21 09:00 UTC
Labels: CKAN (data presentation), EITI Summary data
