### ISSUE TITLE
Add breadcrumb bar to Analysis

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#183] opened 2017-08-31 13:13 UTC
Currently there is nothing there. Preference would be: `Home/Analysis`

![image](https://user-images.githubusercontent.com/19787025/29924901-8f49354e-8e2c-11e7-80c3-0e97e5d74f87.png)

**Comment by mattfullerton** [comment] 2017-09-01 08:46
Duplicate of #176

**Closed by mattfullerton** 2017-09-01 08:46 UTC
Labels: CKAN (data presentation)
