### ISSUE TITLE
RGI source archive: Sort questions by number

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#43] opened 2017-05-15 20:40 UTC
## Why
The questions are not currently sorted by number. That seems as the most logical way to approach this. Would it be possible to list the questions numerically: 

001: ...
002: ... 
003:...

![image](https://cloud.githubusercontent.com/assets/1101585/26078300/05fa0140-398d-11e7-8fbf-9a54bd899ee3.png)

**Comment by mattfullerton** [comment] 2017-05-16 07:21
It depends on what we want :-) I already have a sorting function in there (for reasons I won't go into), so its a ~1-minute change. However, that breaks the standard CKAN functionality of sorting facet values by number of datasets matching that facet value.

Note also that by default first the most popular are shown, and not all values.

**Comment by anderspeders** [comment] 2017-05-22 10:18
Let us keep it as it is sorted by appearance by number of datasets. Closing until this may reappear.

**Comment by moman822** [comment] 2017-09-01 12:54
Reopening and requesting that we change this to alphabetical/numeric ordering and show all values by default. If we can test that out on staging then we can make a final decision. It is still a quick change right @mattfullerton ?

**Comment by mattfullerton** [comment] 2017-09-02 20:08
Duplicate of #179 - @moman822 , it's already on staging: https://staging.resourcedata.org/document?_question_limit=0

**Closed by mattfullerton** 2017-09-02 20:08 UTC
Labels: RGI source library
