### ISSUE TITLE
Front page link to RGI source library broken

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#191] opened 2017-09-12 20:45 UTC
## Why

![image](https://user-images.githubusercontent.com/1101585/30347277-8ec05948-97d9-11e7-8dd7-5bee30ea118a.png)

Front page links to: https://www.resourcedata.org/organization/resource-governance-index

It should link to: https://www.resourcedata.org/organization/rgi

In addition the "globe" logo from the RGI is now missing.

**Comment by moman822** [comment] 2017-09-12 20:55
@mattfullerton can you advise as to why the custom image I keep adding to the RGI organization is getting lost?

**Comment by mattfullerton** [comment] 2017-09-13 08:17
@moman822 That depends on the definition of "keep" but it's probably because the import is replacing it with something else:
https://github.com/NRGI/resourcedata.org/blob/master/harvesters/rgi/scripts/rgi_import.py#L154

Do you have a URL for the globe logo?

@anderspeders That link is fixed on staging; there was already a (now closed) issue: https://github.com/NRGI/resourcedata.org/issues/173

I think we need to get better at a) Checking for existing issues before opening new ones (NRGI), b) Checking for a problem on staging.resourcedata.org if there is one on www.resourcedata.org to see if the problem is already solved (NRGI) and c) Organize a better schedule for pushing staging to production (Derilinx)

In this instance I'd like to wait until the SOLR index is sorted on staging (see #163) and either @moman822 or @anderspeders has had a general browse through staging before deploying to production; a lot of small changes have been made recently, without a push to production.

**Comment by anderspeders** [comment] 2017-09-13 11:59
Ok, thanks @mattfullerton. Noted on a) and b)

**Comment by moman822** [comment] 2017-09-13 12:18
@mattfullerton I've added it twice and it has been lost twice. When it gets lost, there is nothing replacing it. I don't have a URL because it's a screencap I took from a bigger image somewhere on the RGI website. What is the long-term solution for this, stop the import from overwriting the image?

**Comment by mattfullerton** [comment] 2017-09-13 13:52
That'll be easiest... I'll just stop creating/updating the organization completely

**Comment by mattfullerton** [comment] 2017-09-15 15:00
Fix is made to prevent blowing away that log, and production is updated with latest code including the rgi link fix.

However, I'm wondering if the logo problem is another: it's using some kind of CKAN file store which we don't use for files. Maybe @iprunache can advise if that filestore for general uploads (i.e. organization logos) is getting lost everytime we do a rebuild?

cc @NRGI/vitamin @NRGI/vitaminsoftware

**Comment by moman822** [comment] 2017-09-18 18:46
@mattfullerton it is gone again on production

**Comment by mattfullerton** [comment] 2017-09-19 18:44
We did a rebuild of production and I'm sticking with my theory that the file store/s3 store got blown away. See #168

**Comment by mattfullerton** [comment] 2017-09-20 07:29
Here's a more straightforward theory: we _know_ that the filestore gets blown away with each build, because we thought we didn't need it. And I'm fairly certain that these org/group logos go directly into the filestore without any chance of intervention by the s3 extension. So, solutions:

- We persist that filestore folder as a volume (/var/lib/ckan) even though that's kind of annoying - but it won't be very big or change very often
- We disable the file-based storage completely. I would hope that that doesn't break the s3 extension but it might. Also that doesn't solve @moman822 problem of having a file he needs to upload
- We host the file at a URL. Perhaps NRGI has an S3 folder somewhere for image resources etc.? This really might be the easiest option, then we could try the second to stop people uploading things that will get thrown away later.

Passing this to @iprunache

**Comment by iprunache** [comment] 2017-09-21 07:04
@mattfullerton @moman822 Matt's theory is correct, manual uploads still go to the local storage despite the S3 configuration and we loose them on every deploy.

Let's host the logo at an URL. @moman822 If you don't have a place to store it then add it to this thread as an attachment and I'll drop it in an S3 bucket and link it from there.

We don't have an easy solution for persisting the filestore folder as a Docker volume because the ResourceData container can be deployed randomly on any of 6 container instances with each deploy. We would have to use some shared network drive between the instances which complicates things too much.

**Comment by moman822** [comment] 2017-09-21 20:10
@iprunache thanks, here is the file.

![info2](https://user-images.githubusercontent.com/19787025/30716240-51d8ec42-9ee7-11e7-9583-79047b53fbe9.PNG)

**Comment by iprunache** [comment] 2017-09-29 20:15
@mattfullerton @moman822 I don't know how this happened but user uploads are now stored on the AWS S3 bucket. Looks like CKAN created the necessary folder structure and made the uploads public. It should be safe to upload files now but keep in mind that they become public.

Here's a screenshot:
<img width="1622" alt="screen shot 2017-09-29 at 23 10 59" src="https://user-images.githubusercontent.com/15313824/31034253-ee782a9c-a56b-11e7-9bf7-6f0bed608a78.png">

@moman822 please close this if all outstanding issues are fixed.

**Comment by mattfullerton** [comment] 2017-10-09 09:38
@moman822 Can we close this?

**Closed** 2017-10-09 12:11 UTC
Labels: CKAN (data presentation) - purely UI
