### ISSUE TITLE
Authorative list of countries (was: Duplicate datasets)

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#25] opened 2017-05-03 16:57 UTC
## Why

Number of countries in the EITI data have duplicate datasets. For example US: 
![image](https://cloud.githubusercontent.com/assets/1101585/25671984/ec50f6a4-2fff-11e7-9917-83d36ef18efb.png)
 
http://resourcedata.org/dataset/eiti-summary-data-table-for-united-states-of-america 

What can we do to clean this up?

**Comment by moman822** [comment] 2017-05-03 17:37
Countries with duplicates, as above:

USA: http://resourcedata.org/dataset/eiti-summary-data-table-for-united-states-of-america
Tanzania: http://resourcedata.org/dataset/eiti-summary-data-table-for-tanzania
Republic of Congo: http://resourcedata.org/dataset/eiti-summary-data-table-for-republic-of-the-congo
Kyrgyz Republic: http://resourcedata.org/dataset/eiti-summary-data-table-for-kyrgyz-republic
DRC: http://resourcedata.org/dataset/eiti-summary-data-table-for-democratic-republic-of-congo

**Comment by moman822** [comment] 2017-05-03 17:42
Related to this issue: the "Additional Info" table is not correctly filled out on these five dataset pages.

See: USA
![image](https://cloud.githubusercontent.com/assets/19787025/25673702/3aa13796-3006-11e7-816d-9f832de909a5.png)

vs. Zambia

![image](https://cloud.githubusercontent.com/assets/19787025/25673718/49179946-3006-11e7-926d-af06bac1807d.png)

**Comment by iprunache** [comment] 2017-05-04 08:53
This is a duplicate of #8. The countries identified are the same mentioned in the comments of #8.

**Comment by mattfullerton** [comment] 2017-05-05 10:12
What was happening is this: for some reason those host country datasets did get created successfully at some point; but by now creation (and, crucially, updating) is not longer possible because of the schema check ("409 {u'help': u'http://www.resourcedata.org/api/3/action/help_show?name=package_update', u'success': False, u'error': {u'country': [u"Value must be one of: Aruba...." in #8). The creation happened presumable before we had these new (checked) fields and that is why the additional data is missing @moman822. 

When updating (with an empty resource set, which is what we currently do) fails, the current set of resources is not wiped out and hence we end up with duplicate resources.

The fix is two fold:
- Delete the countries with bad data

And either:
- Change the country names in the schema in ckanext-nrgi (https://github.com/derilinx/ckanext-nrgi/blob/master/ckanext/nrgi/schema.json#L766) to match those from EITI (the names are funneled directly through from their API) and reinstall that extension
- Change the script to map EITI country names to the ones in the schema.

I assume we want the latter because the country names have to be a common set that also work for RGI?

**Comment by anderspeders** [comment] 2017-05-05 23:57
Here's another similar issue for Tanzania: 

![image](https://cloud.githubusercontent.com/assets/1101585/25768013/05034264-31cd-11e7-8913-8471d4ec7a19.png)

**Comment by mattfullerton** [comment] 2017-05-09 14:52
We need to answer the question above, and then all of these examples will get fixed - its the same problem everywhere.

Since making that write up I was told we should try and stick to the official naming of countries: http://publications.europa.eu/mdr/resource/authority/country/html/countries-eng.html

As far as I can see, the EITI country names are conforming better with ISO names (http://publications.europa.eu/mdr/resource/authority/country/html/countries-eng.html) than with the schema we have right now (https://github.com/derilinx/ckanext-nrgi-published/blob/master/ckanext/nrgi/schema.json#L766). But its not perfect, e.g. ISO is Democratic Republic of _the_ Congo and EITI is Democratic Republic of Congo. Do we have any idea/code for what EITI base their API on?

**Comment by mattfullerton** [comment] 2017-05-15 10:07
This is taken care of provisionally now, e.g.:
http://resourcedata.org/dataset/eiti-summary-data-table-for-democratic-republic-of-congo

"Bad" country names in the EITI import are mapped to those we have in the schema. I still want to look and see if we can standardize our country names better at which point a reimport can fix the names.

**Comment by mattfullerton** [comment] 2017-05-19 12:55
Removing the priority label on this one

**Comment by moman822** [comment] 2017-06-20 18:59
this is still present on staging server

@mattfullerton @iprunache 

see: https://staging.resourcedata.org/dataset/eiti-summary-data-table-for-tanzania

**Comment by iprunache** [comment] 2017-06-20 22:06
I think that's because we haven't run an EITI import on staging in a long time. We're doing it daily for production only. I'm triggering a manual run now.

**Comment by mattfullerton** [comment] 2017-06-21 04:02
@iprunache I only see GET requests for that dataset in the logs, no POSTs so I assume the update didn't run yet. Please let me know once it does.

Especially for EITI and for staging its feasible for me to do an import from here but I need an admin account/API key.

**Comment by iprunache** [comment] 2017-06-21 16:48
@moman822 the EITI import run on staging finished and Tanzania is clean now. Please give it a look and close this if you're satisfied.

/cc @mattfullerton

**Comment by moman822** [comment] 2017-06-21 18:10
lookgs good,

**Closed by moman822** 2017-06-21 18:10 UTC
Labels: EITI Summary data, priority
