### ISSUE TITLE
No datasets displayed

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#181] opened 2017-08-31 08:40 UTC
Although 2 available datasets are noted for Côte d’Ivoire none are shown when clicking on the link. 

![image](https://user-images.githubusercontent.com/13888372/29914207-fb4e1894-8e37-11e7-8181-83fd1611b2bb.png)

**Comment by mattfullerton** [comment] 2017-08-31 12:15
Duplicate of #163

**Comment by mattfullerton** [comment] 2017-08-31 12:15
Because the link itself is wrong and is sending it to the wrong search page

**Closed by mattfullerton** 2017-08-31 12:15 UTC
